version: '3'
services:
  nodejs-server:
    image: dpontius32/nodejs
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  angular-ui:
    image: dpontius32/angular-app
    ports:
      - "4201:4201"
    container_name: angular-ui
    volumes:
       - ./app-ui:/usr/src/app/app-ui
       - /usr/src/app/app-ui/node_modules